---
- name: Sample
  hosts: localhost
  gather_facts: false

  vars:
    var_message: Hello message!

  tasks:
    - name: Debug msg
      ansible.builtin.debug:
        msg: Hello Ansible!

    - name: Debug var_message
      ansible.builtin.debug:
        var: var_message
