---
version: 3
 
images:
  base_image:
    name: rockylinux:9.2
 
dependencies:
  python_interpreter:
    package_system: python3.9
    python_path: /usr/bin/python3
  ansible_core:
    package_pip: ansible-core~=2.14
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: ansible.utils
      - name: community.general
      - name: vyos.vyos
  python:
    - ansible-pylibssh
    - jmespath
  system:
    - sshpass
    - openssh-clients
    - iputils
    - iproute
    - traceroute
 
additional_build_steps:
  append_base:
    - RUN pip3 install --upgrade pip setuptools
  prepend_final:
    - RUN rm -f /etc/localtime
    - RUN ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
