---
- name: sample1
  hosts: all
  gather_facts: false

  tasks:
    - name: Execute show commands to vyos01 and vyos02
      vyos.vyos.vyos_command:
        commands: 
          - show ip route
      register: result
      when: inventory_hostname == 'vyos01' or inventory_hostname == 'vyos02'

    - name: Display result
      ansible.builtin.debug:
        var: result.stdout_lines