---
- name: sample
  hosts: localhost
  gather_facts: false

  tasks:
    - name: make directory
      file:
        path: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/file_directory
        state: directory

# pathが違う
# FQCNじゃないのは問題ない=統一感がない？