---
- name: sample
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Create exam3.txt"
      ansible.builtin.file:
        path: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/exam3.txt
        state: touch

    - name: "Copy exam3.txt to copy_directory"
      ansible.builtin.copy:
        src: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/exam3.txt
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/copy_directory

# markdownがexam3.txtになっていない